language: php

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

php:
  - 7.2
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - composer clear-cache

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      name: "PHP Codesniffer: PSR2"
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=phpu/tools --working-dir=../tools
        - composer require friendsofphp/php-cs-fixer:^2.12 --working-dir=../tools
      install: true
      script:
        - ../tools/vendor/bin/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff
    - stage: Static Code Analysis
      php: 7.2
      name: PHPstan
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=phpu/tools --working-dir=../tools
        - composer require phpstan/phpstan:^0.10 --working-dir=../tools
      install: composer update
      script:
        - ../tools/vendor/bin/phpstan analyse --level max src tests